# Generated by Django 3.2.7 on 2021-09-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210904_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='tasks',
            field=models.ManyToManyField(to='main_app.Task'),
        ),
    ]
