# Generated by Django 3.2.7 on 2021-09-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_bread_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.IntegerField(),
        ),
    ]
