# Generated by Django 3.2.7 on 2021-09-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_task_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
