# Generated by Django 3.2.7 on 2021-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210905_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(),
        ),
    ]
