# Generated by Django 3.2.7 on 2021-09-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210905_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='minutes',
            field=models.CharField(max_length=10),
        ),
    ]
