# Generated by Django 3.2.7 on 2021-09-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210906_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='minutes',
            field=models.CharField(max_length=3),
        ),
    ]
