# Generated by Django 3.2.7 on 2021-09-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210906_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bread',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='bread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.bread'),
            preserve_default=False,
        ),
    ]
