# Generated by Django 3.2.7 on 2021-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210906_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='minutes',
            field=models.CharField(max_length=2),
        ),
    ]
