# Generated by Django 3.2.7 on 2021-09-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_task_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bread',
        ),
    ]
