# Generated by Django 3.2.7 on 2021-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_task_bread'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='tasks',
            field=models.ManyToManyField(to='main_app.Task'),
        ),
    ]
