# Generated by Django 3.2.7 on 2021-09-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
