# Generated by Django 3.2.7 on 2021-09-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210908_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
